# create your drupal and postgres config here, based off the last assignment
version: "2"

services:
  drupal:
          image: custom-drupal
          build:
            context: .
          ports:
            - "8080:80"
          environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
          volumes:
            - drupal-modules:/var/www/html/modules
            - drupal-profiles:/var/www/html/profiles
            - drupal-sites:/var/www/html/sites
            - drupal-themes:/var/www/html/themes
  postgres:
    image: "postgres:12.1"
    environment:
      POSTGRES_PASSWORD: admin
    volumes: 
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-data:

